spring:
  profiles:
    active: dev
---
server:
  prot: 8201
#Spring的配置
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept     #服务名称 - 服务之间使用名称进行通讯
  

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://eureka7001.com:7001/eureka/

---
server:
  prot: 8202
#Spring的配置
spring:
  profiles: test
  application:
    name: springcloud-provider-dept     #服务名称 - 服务之间使用名称进行通讯
  

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://eureka7001.com:7001/eureka/