spring:
  profiles:
    active: dev

---
server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.gao.springcloud.domain
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#Spring的配置
spring:
  profiles: dev
  application:
    name: springcloud-config-dept     #服务名称 - 服务之间使用名称进行通讯
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:
      instance-id: springcloud-provider-dept8001    #修改eureka上的默认描述信息
    # 是否需要将自己注册到注册中心
    register-with-eureka: true
    # 是否需要搜索服务信息
    fetch-registry: true


#info 配置
info:
  app.name: springcloud-study
  company.name: gao.com

---
server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.gao.springcloud.domain
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#Spring的配置
spring:
  profiles: test
  application:
    name: springcloud-config-dept     #服务名称 - 服务之间使用名称进行通讯
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:
      instance-id: springcloud-provider-dept8001    #修改eureka上的默认描述信息
    # 是否需要将自己注册到注册中心
    register-with-eureka: true
    # 是否需要搜索服务信息
    fetch-registry: true


#info 配置
info:
  app.name: springcloud-study
  company.name: gao.com